# Generated by Django 5.0 on 2024-01-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playername', models.CharField(max_length=40)),
                ('playerage', models.DateField()),
                ('imagem', models.IntegerField(null=True)),
            ],
        ),
    ]
