# Generated by Django 5.0 on 2024-01-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='funcao',
            field=models.IntegerField(null=True),
        ),
    ]
